# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               '오늘도 뚜벅뚜벅'
tagline:             ''
description:         ''
url:                 http://SehwanKwak.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sehwan kwak
  url:               https://SehwanKwak.github.io
  email:             sehwan.kwak@gmail.com

# Custom vars
version:             1.0.0

plugins:
  - jekyll-paginate

